### ISSUE TITLE
error after start importlib_resources

### ISSUE THREAD

**Issue by AlreadyNobody** [fkie-cad/friTap#11]
Traceback (most recent call last):
  File "d:\python\python_original\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "d:\python\python_original\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "D:\python\python_original\Scripts\friTap.exe\__main__.py", line 4, in <module>
  File "d:\python\python_original\lib\site-packages\friTap\friTap.py", line 16, in <module>
    import friTap.pcap as pcap
  File "d:\python\python_original\lib\site-packages\friTap\pcap.py", line 16, in <module>
    import friTap.android as android
  File "d:\python\python_original\lib\site-packages\friTap\android.py", line 14, in <module>
    from importlib_resources import files
ModuleNotFoundError: No module named 'importlib_resources'

**Comment by Android-Unknown** [comment]
@AlreadyNobody 
`pip install importlib-resources`

**Comment by monkeywave** [comment]
With the latest release (1.1.0.1) this is integrated into the requirements.txt.
