### ISSUE TITLE
AttributeError: 'PCAP' object has no attribute 'full_capture_thread'

### ISSUE THREAD

**Issue by lilili87222** [fkie-cad/friTap#34]
[*] Target process stopped: process-terminated

Traceback (most recent call last):
  File "/Users/admin/.pyenv/versions/3.11.10/lib/python3.11/site-packages/friTap/ssl_logger.py", line 126, in on_detach
    self.cleanup(self.live,self.socket_trace,self.full_capture,self.debug)
  File "/Users/admin/.pyenv/versions/3.11.10/lib/python3.11/site-packages/friTap/ssl_logger.py", line 564, in cleanup
    if self.pcap_obj.full_capture_thread.is_alive():
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'PCAP' object has no attribute 'full_capture_thread'

**Comment by warinium** [comment]
Same for me

**Comment by lilili87222** [comment]
1.2.64 fixed
